[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0530c73fcffbf90e41abbe7e998349b6987977e8"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "e9b4e5e602c83877063cb8c05503f6e40d444a3eb81cd78b42fa64c2f3eb028d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.aarch64-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67573561a63c14371d57749289e733cb7622f201"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "f961f6ecaa02a105b7cfd352ef86ba757aa7f339d6dbad54ac23a73f382d216c"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.aarch64-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abe8933c81cc0427ce80c0873d1c3941046f6efe"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "9e9fc0fa93ad2e34e3f274318f133997e021482fe8a51ab51b7192fcb4a04b0a"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.aarch64-linux-musl-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a25c0a2811c8d250f272f56cd1746da1b131f1f"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "a3bf9233b4fb44d95611e96949ae1952d346bd499bd9efea0b311cee90d0891a"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.aarch64-linux-musl-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2895903ec0585a7e14412bae4b7067c1cec8c711"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "9b6ad15fde949cab1950dc632fbe9a67000f2389a3a1b06859834dc1a86ebbf2"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18d399185231c2fd54ae0c3251c232f5f956be52"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "70fe22c14fce76c55f0449985e54e0025b410ec4d754ad6cfcdcde171ce6b037"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f31016334b1c13f6e55826f5f39b52d10dc603a"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "49053130cbb738c05f91ecdbccfc7ff4b94bc61baa675257cc759bc9aaeeeaac"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ad0ef42e8fa45fa13962e46531671440e4eaa85"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "a8b6f3101cdd7d16a9c840b8a40ea81b74ebf3ed8ab491d9f92716f9c92931ab"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d34912bf14a59cde1f974b27a4749ba4b10f6b76"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "c8171996ae487e1352af039df38f44f8015a3f099d3ac0c3057bab1113328e62"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.i686-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "54d5c4f646e1e20dab385f4fd8b32057e7696046"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "ab9d98b3c306c4b6bfa476062f6613bdc9b1ddf03ea3c995b973482b003b5c51"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.i686-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a401b1acf465638c5bf64771c171983379c81c8f"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "9ec9410abb37775dafb09495f0cc2d884bdfeb3138996b828810fe3f2da7214b"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e588fbb2510c1e67f1ad435692930be7ea2c49d"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "b20282427b3553ea406a6679eabb71028d8247ddb5df539740e0062fdafda5c9"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "e2eacad5f2a1a4c9b7ab3e314cb32bcd676b81b4"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "2ba66cc20251f4baf90b4e2374a420fa02b50800f2479da4a407eef2fa020117"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.x86_64-apple-darwin.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2011514d5c50e3915a3803333dd799a3bcc0d7fb"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "cc462f8ac6334f4681c0ae11cfbcbd1d32ccd53738483c12cd6fb4df3a5678d2"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.x86_64-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13cf49f08bb6b5ab3e6c7f5367fef303c0a9d0d4"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "14b5f51d521f0ed5d2fcbd306ce02c117615263b72777071a37f8355219dad01"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.x86_64-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53a2eed2cb7e83025ad23bf369de422a486252b1"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "be5e0599dae7cad705a139b4c1b944f02f43c5ae5df0ee44e5a26e2e0dcb94ce"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.x86_64-linux-musl-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46cadb8d221565c8cf6598fdd90252d207517e35"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "4f9d8a80a9f123086cea479163c674f5f87e26029ea4b7e977af133bd1ceb57e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.x86_64-linux-musl-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "b2e20a8e32772ba69c86461d9e2762c8792b4236"
os = "freebsd"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "9fb314963f4845d33275af927b1f124f688f1fce0229a1eb9b7f269d7c164c29"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.5+2/FastJet_Julia_Wrapper.v0.8.5.x86_64-unknown-freebsd.tar.gz"
