[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24cb87ebfd8798ee94ba1d2e36f5f5fc0ca527e1"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "f957e34ee0212d604cf6477246238678ca5fd026169bf9e21a5d6fb40ad753b2"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.4+0/FastJet_Julia_Wrapper.v0.8.4.x86_64-apple-darwin14-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fa017e22fb055b1511fedaab0e2faf332903414"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "67c6f87df1738c794038a4173cd6fd98de8c3171725cbdea799792aebef634e2"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.4+0/FastJet_Julia_Wrapper.v0.8.4.x86_64-linux-gnu-cxx11.tar.gz"
