[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7db7aba4bf6e1e083a0fe0ae8c516bb8f85ebc60"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "2c1a1bf33cb7fdaae8ad527af7b32646ce48440bde2b4ea3890fc5139e21e2d9"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.0+0/FastJet_Julia_Wrapper.v0.7.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61426f2462541916880459efccc0946918497c0f"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "d303623b43d31d8f30afe7dd8471f6cdf215cca72e90c2aa33fc06d174c44f3a"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.0+0/FastJet_Julia_Wrapper.v0.7.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4080dd0e5445fb4b0fe50a844a0cd4d27ae5824c"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "6245a1d02a28bd139cdabf43f6c2c2623b1825f1086ef48d181f3d5dd32ff9e2"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.0+0/FastJet_Julia_Wrapper.v0.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb4cac8730093a80f3e5d95d7e3c1936bc2a3abb"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "486613be5ce37aaae9d75d4509daa6ffd409dc5784e57a6a6470d417ca1ce9ab"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.7.0+0/FastJet_Julia_Wrapper.v0.7.0.x86_64-linux-gnu-cxx03.tar.gz"
