[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb9d1464b1674c3920ec3cdaae95882dc9c7af3b"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "2be58cefe56ab43fcaefd82676f0421ae3c58a961b62ee036b59a5d9f5401e7d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.0+0/FastJet_Julia_Wrapper.v0.8.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9171582cd24db701a1ae006cb07f71cfd1e79f59"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "7573016ab841b451d99594b8b12243348f42a07ccd897f4db2032fce02d9fab8"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.0+0/FastJet_Julia_Wrapper.v0.8.0.x86_64-linux-gnu-cxx11.tar.gz"
