[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87de68e253e9d57841193e9e6e5e5d8b27c8b822"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "9105215d64af22eef888ae51410a424c9965dfbe2ca75b1f38af5122e44ef2c1"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.2+0/FastJet_Julia_Wrapper.v0.8.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c7126a40ede44eaa94401587486e2ca8211f0a3"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "dce6b952361304ca63f6b01af614e824da216fd865b635bdf4d33463cf5cafd6"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.2+0/FastJet_Julia_Wrapper.v0.8.2.x86_64-linux-gnu-cxx11.tar.gz"
