[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af735a4d1c877ef5e5bde5145a231221b8c5a1a2"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "9301fb174ec354f7b1937e6c1889c4c73399e9dde64362de6773ec12d179b636"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.aarch64-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99d73716ea8d33b9a35552d5689aaf78c6fa2df3"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "e23018a23c6e7790acae579ada70518cd8a59a7bc4657948d90cd4208c61412d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.aarch64-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8250dbfe1b92d56fd155435884a003eed420a188"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "57c39e79d6d7e64fda035f8a92ad3e3df2669d34d86e311383b44cf857e0f778"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.aarch64-linux-musl-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d9d859c39cd4828d08174048c93798842e86192"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "74d227010865e9187f9a5c40811664651648c8ab965f2079eb702762b41a7b4e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.aarch64-linux-musl-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d24d18f9413ed11aa2f4e390c3e99a53b00c4b9d"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "d3ed70c9a0fb90432c6a7ab21bd915d339331f83b491f5158d41578fe9fad2e7"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d657622da1db195898285551e5ec8c4457557a8"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "e3fe3b6fc3d2a009289a4ed8997bd351afa43ed694d16cd958f46cda720d96f2"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf61e4ad30a5d955b9d4a0dda659ff707640593a"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "ce4cf1baa92bc6a068fb4e3caf92ac51722e568a619f27254e1fee5cefb6a297"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a36d1959b401519077c3be1166ef7046a2ba135"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "8dd4f92c4c1125bf649f387ef1d61b1d9b9951dfa0dab4e9b45c4fffedf358b1"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "551e5c4652e2059d5ecd6e957a617aa96baa2bcd"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "82a0def101e4adb2aeef95a98368f3e064352f84d2fb3554054c69637410ba33"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.i686-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6bdca207fd3bad32b696a23f8208a55592df2b8"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "a28ec9cb6afa95a8e0f4880a1cb4d1a88e8de5de5947212d6c4e499347af3122"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.i686-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b341433f6f48607afc7cda5dca65ac25d0187370"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "cb28f135b28d3c82feb2450d43461d5ffe2b6fb8e508d9c4fa30444c4d56664d"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66da2227d0db21e5a9fb029bf7252334a4d78f02"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "48841913b690bce5b11bcc37a2eef694a4ce69e93b5f187f69fd502ba451275b"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "7b8bda816f31988bd935745deb1a5913718d991e"
os = "macos"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "452a6db46779e3b3cce0255f01956e5bef9169a1a958f02c2713372634c21f5e"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.x86_64-apple-darwin.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0421770bdd49d0ed1d61fbd05f8f57a822c4749"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "68f0a139e458d6971c8c51eda6b7f9123a88c46e0a543936229701f2d6df8053"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.x86_64-linux-gnu-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1346ceb8cd1b1f1c685c7dbe5e25fb09ee75ae24"
libc = "glibc"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "fbbed492725ab034fcddbde3dfaa3ba866dfbd17765bf4811533b5e86cc82757"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.x86_64-linux-gnu-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f891419c8ef6618563092ea0c108500dff0cdf26"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "26d82562432226cb3af6f1483ffca3aceaee06b20436dc952cdcf1f78e29b7cf"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.x86_64-linux-musl-cxx03.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4d8201c8131c0ad8ab3c09eddb43086970c325d"
libc = "musl"
os = "linux"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "88752d03f0a4625774534ca02c56f7a667724d81f6d82164e6260802b600cebb"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.x86_64-linux-musl-cxx11.tar.gz"
[[FastJet_Julia_Wrapper]]
arch = "x86_64"
git-tree-sha1 = "2d3ab55b1045e75b950a93c4e1e5aab984504f4e"
os = "freebsd"

    [[FastJet_Julia_Wrapper.download]]
    sha256 = "3f31157ac5cd545ed0bc679f3d7a0da753ea730c0efd52f39f5de77349b9fb86"
    url = "https://github.com/JuliaBinaryWrappers/FastJet_Julia_Wrapper_jll.jl/releases/download/FastJet_Julia_Wrapper-v0.8.6+0/FastJet_Julia_Wrapper.v0.8.6.x86_64-unknown-freebsd.tar.gz"
